# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/gamegenerator.proto for package ''

require "grpc"
require "proto/gamegenerator_pb"

module GameGenerator
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = "GameGenerator"

    rpc :GenerateGame, ::GenerateGameRequest, ::GenerateGameResponse
  end

  Stub = Service.rpc_stub_class
end
