# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/gamegenerator.proto for package 'unitygen'

require "grpc"
require "proto/gamegenerator_pb"

module Unitygen
  module GameGenerator
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "unitygen.GameGenerator"

      rpc :GenerateGame, ::Unitygen::GenerateGameRequest, ::Unitygen::GenerateGameResponse
    end

    Stub = Service.rpc_stub_class
  end
end
